### PR TITLE
Added support for  the schedule

### PR DESCRIPTION
**Pull request by hajee**
This PR makes sure the echo adheres the specified schedule.

### CODE REVIEW

**Comment by hajee** [comment]
@ipcrm can you take a look at why the tests are not running ?

**Comment by hajee** [comment]
Any reaction would be greatly appreciated?

**Comment by gabe-sky** [comment]
Nice addition.  Thanks!

**Comment by ipcrm** [comment]
@hajee My apologies on the slow response, I'll take a look.

**Comment by ipcrm** [comment]
@hajee Looks like the build did run but the check didn't register as failed for some reason.  Details here: https://travis-ci.org/github/ipcrm/ipcrm-echo/jobs/739668629

Looks like there was a failure.

**Comment by hajee** [comment]
Thanks @ipcrm I have fixed that and force pushed.

**Comment by ipcrm** [comment]
awesome! thx @hajee

**Pull request merged**
